/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_engine_free: (a: number, b: number) => void;
export const engine_build_navmesh: (a: number) => void;
export const engine_build_navmesh_2d: (a: number, b: number, c: number, d: number) => void;
export const engine_clear_monster_capability: (a: number, b: number) => void;
export const engine_clear_monster_goal: (a: number, b: number) => void;
export const engine_deserialize_patch: (a: number, b: number) => any;
export const engine_destroy_entity: (a: number, b: number) => void;
export const engine_dimension: (a: number) => [number, number];
export const engine_find_path: (a: number, b: number, c: number, d: number, e: number, f: number, g: number) => any;
export const engine_get_metrics: (a: number) => any;
export const engine_load_map: (a: number, b: any) => any;
export const engine_net_ingest: (a: number, b: number, c: number, d: number, e: number) => void;
export const engine_net_peer_connected: (a: number, b: number, c: number) => void;
export const engine_net_peer_disconnected: (a: number, b: number, c: number) => void;
export const engine_net_take_outbound: (a: number) => any;
export const engine_new: (a: number, b: number, c: number) => number;
export const engine_player_fire: (a: number) => void;
export const engine_register_player: (a: number, b: number) => void;
export const engine_set_ai_config: (a: number, b: any) => void;
export const engine_set_entity_velocity: (a: number, b: number, c: number, d: number, e: number) => void;
export const engine_set_log_level: (a: number, b: number) => void;
export const engine_set_monster_capability: (a: number, b: number, c: any) => void;
export const engine_set_monster_config: (a: number, b: any) => void;
export const engine_set_monster_goal: (a: number, b: number, c: number, d: number) => void;
export const engine_set_nav_config: (a: number, b: any) => void;
export const engine_set_player_config: (a: number, b: any) => void;
export const engine_set_player_input: (a: number, b: any) => void;
export const engine_set_terrain_walkable: (a: number, b: number, c: number) => void;
export const engine_spawn_box_entity: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number) => number;
export const engine_spawn_bullet: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number) => number;
export const engine_spawn_entity: (a: number, b: number, c: number) => number;
export const engine_spawn_floor_entity: (a: number, b: number, c: number, d: number, e: number, f: number, g: number) => number;
export const engine_spawn_monsters: (a: number, b: number) => void;
export const engine_teleport_entity: (a: number, b: number, c: number, d: number, e: number) => void;
export const engine_tick: (a: number, b: number) => any;
export const engine_update_monster_goal: (a: number, b: number, c: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_start: () => void;
