[package]
name = "netcode"
version = "0.1.0"
edition = "2021"

[dependencies]
ecs = { path = "../ecs" }
bincode = { version = "2", features = ["derive"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-peers = "0.4"
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
js-sys = "0.3"
web-sys = { version = "0.3", features = ["console"] }
